### ISSUE TITLE
Unexpected behaviour

### ISSUE THREAD

**Issue by asaharan** [3DIndian/2048#3]
Example state
    2 2 1 1
On press right arrow new state is
    _ 3 _ 2
Expected state
    _ _ 3 2

**Comment by 3DIndian** [comment]
What's the issue with 2211, I was also able to reproduce it, look here: https://screenshots.firefox.com/4JHUIny4YHkoBpxB/3dindian.github.io

**Comment by 3DIndian** [comment]
Alright, will look into this, I have to update dispArray everytime them

**Comment by 3DIndian** [comment]
@asaharan I have submitted a fix, check it and please update

**Comment by asaharan** [comment]
Still not correct
Example:
    Initial state:
    3 3 2 2
   On pressing right arrow new state is
   _ 3 4 3
   Expected state
   _ _ 4 3

**Comment by 3DIndian** [comment]
Bhai maaf kar de :(
